# .github/workflows/issue-on-push.yml
name: Create an issue on push
on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: cider-research-testing/unpinnable-action@main
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
