name: check-pinnable-docker-file-only.yaml
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  issues: write 
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c    
      - run: pwd
      #- run: cat .git/config
      - uses: cider-research-testing/action-docker-file-only@main
      - uses: cider-research-testing/unpinnable-action@main
        with:
         token: ${{ secrets.db_password }}
      - name: Labeler
        uses: actions/labeler@v4.0.3



                  
