name: Docker-File-Only
on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write 
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: cider-research-testing/unpinnable-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - uses: cider-research-testing/action-docker-file-only@main
                  
