name: check-pinnable-docker-file-only.yaml
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  issues: write 
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c    
      - uses: cider-research-testing/unpinnable-action@809b27f9d264dcc93f0984fe025697b52f49eccf
        with:
         token: ${{ secrets.db_password }}
