name: Create an issue on push
on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write 
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: cider-research-testing/unpinnable-action@main
