# .github/workflows/issue-on-push.yml
name: upload-artifact
# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
jobs:
  stuff:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo hi > word.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: word.txt
  stuff2:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: sleep 1
      - run: echo there > word.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: word.txt
  query_workflows:
    runs-on: ubuntu-latest
    permissions: 
      actions: read
    steps:
      - run: sleep 1
      - run: gh api /repos/cider-research-testing/workflow-tester/actions/workflows
        env:
         GH_TOKEN: ${{ github.token }}
  query_artifacts:
    runs-on: ubuntu-latest
    permissions: 
      actions: read
    steps:
      - run: sleep 1
      - run: gh api /repos/cider-research-testing/workflow-tester/actions/runs/${{ github.run_id }}/artifacts
        env:
         GH_TOKEN: ${{ github.token }}
  print_token:
    runs-on: ubuntu-latest
    permissions: 
      actions: none
    steps:
      - run: echo $ACTIONS_RUNTIME_URL
      - run: echo $ACTIONS_RUNTIME_TOKEN | base64
        env:
         GH_TOKEN: ${{ github.token }}
   
   
   


  
