# .github/workflows/issue-on-push.yml
name: upload-artifact
# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
jobs:
  stuff:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo hi > word.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: word.txt
  stuff2:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo there > word.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: word.txt
