# .github/workflows/issue-on-push.yml
on: 
	workflow_dispatch;
name: Upload artifact
permissions:
  contents: read
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt

      

          
